name: project_ginger_one_stop
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  graphql_flutter: ^5.1.2
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  path_provider: ^2.1.5
  video_player: ^2.9.2
  vimeo_video_player: ^0.0.16
  media_kit_native_event_loop: 1.0.9
  logger: ^2.4.0
  mime: ^2.0.0
  flutter_secure_storage: ^9.2.2
  file_saver: ^0.2.14
  http: ^1.2.2
  provider: ^6.1.2
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  http_parser: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
